default_platform(:android)

platform :android do
  lane :beta do
    sh("flutter", "build", "appbundle", "--release")
    upload_to_play_store(
      track: "internal",
      release_status: "completed",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end

  lane :release do
    sh("flutter", "build", "appbundle", "--release")
    upload_to_play_store(
      track: "production",
      release_status: "completed",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
